// Generated. Paths for every Medic Connect email kit asset, served from public/email-kit.
// Emails need absolute URLs, so the render call prefixes these with the public site origin.

export const KIT_ASSET_PATHS: Record<string, string> = {
  "icon-address-blue.png": "/email-kit/icon-address-blue.png",
  "icon-address-white.png": "/email-kit/icon-address-white.png",
  "icon-appointment-blue.png": "/email-kit/icon-appointment-blue.png",
  "icon-appointment-white.png": "/email-kit/icon-appointment-white.png",
  "icon-email-blue.png": "/email-kit/icon-email-blue.png",
  "icon-email-white.png": "/email-kit/icon-email-white.png",
  "icon-hours-blue.png": "/email-kit/icon-hours-blue.png",
  "icon-hours-white.png": "/email-kit/icon-hours-white.png",
  "icon-included-blue.png": "/email-kit/icon-included-blue.png",
  "icon-included-white.png": "/email-kit/icon-included-white.png",
  "icon-next-blue.png": "/email-kit/icon-next-blue.png",
  "icon-next-white.png": "/email-kit/icon-next-white.png",
  "icon-phone-blue.png": "/email-kit/icon-phone-blue.png",
  "icon-phone-white.png": "/email-kit/icon-phone-white.png",
  "icon-supervised-blue.png": "/email-kit/icon-supervised-blue.png",
  "icon-supervised-white.png": "/email-kit/icon-supervised-white.png",
  "m-cross-blue.png": "/email-kit/m-cross-blue.png",
  "m-cross-tint.png": "/email-kit/m-cross-tint.png",
  "m-full-soft.png": "/email-kit/m-full-soft.png",
  "m-full-white.png": "/email-kit/m-full-white.png",
  "m-inf-soft.png": "/email-kit/m-inf-soft.png",
  "medicconnect-logo-white.png": "/email-kit/medicconnect-logo-white.png",
  "medicconnect-logo.png": "/email-kit/medicconnect-logo.png",
  "social-facebook-blue.png": "/email-kit/social-facebook-blue.png",
  "social-facebook-white.png": "/email-kit/social-facebook-white.png",
  "social-instagram-blue.png": "/email-kit/social-instagram-blue.png",
  "social-instagram-white.png": "/email-kit/social-instagram-white.png",
  "social-linkedin-blue.png": "/email-kit/social-linkedin-blue.png",
  "social-linkedin-white.png": "/email-kit/social-linkedin-white.png",
  "social-whatsapp-blue.png": "/email-kit/social-whatsapp-blue.png",
  "social-whatsapp-white.png": "/email-kit/social-whatsapp-white.png"
};
